// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIgN_Wbe4097iQ5GWGc5Z0bRpSR_uxqc',
    appId: '1:557111722654:web:0e486c684d4cdd97ed718f',
    messagingSenderId: '557111722654',
    projectId: 'emergency-phone-project-2824f',
    authDomain: 'emergency-phone-project-2824f.firebaseapp.com',
    storageBucket: 'emergency-phone-project-2824f.appspot.com',
    measurementId: 'G-MVGQ51D0WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhF4G4uY0C3It75wMn-9X8Cqfn1PcTNyw',
    appId: '1:557111722654:android:68c2334265c724bded718f',
    messagingSenderId: '557111722654',
    projectId: 'emergency-phone-project-2824f',
    storageBucket: 'emergency-phone-project-2824f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDOGJuapcHXWpraxN1c_Yqqnk8XaEsthg',
    appId: '1:557111722654:ios:9b82505b98c78b76ed718f',
    messagingSenderId: '557111722654',
    projectId: 'emergency-phone-project-2824f',
    storageBucket: 'emergency-phone-project-2824f.appspot.com',
    iosClientId: '557111722654-2dsddldev9bse8i3qgksikj0642b6r9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDOGJuapcHXWpraxN1c_Yqqnk8XaEsthg',
    appId: '1:557111722654:ios:9b82505b98c78b76ed718f',
    messagingSenderId: '557111722654',
    projectId: 'emergency-phone-project-2824f',
    storageBucket: 'emergency-phone-project-2824f.appspot.com',
    iosClientId: '557111722654-2dsddldev9bse8i3qgksikj0642b6r9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyPhone',
  );
}
